exclude: ["node_modules", "gulpfile.js", "package.json", "Gemfile", "Gemfile.lock"]

social-links:
  twitter: 'https://twitter.com/netlify'
  facebook: 'https://www.facebook.com/netlify'
  github: 'https://github.com/netlify'
  linkedin: 'https://www.linkedin.com/company/netlify'
  googleplus: 'https://plus.google.com/+NetlifyApp'


excerpt_separator: <!-- excerpt -->

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"