exclude: ["node_modules", "gulpfile.js", "package.json", "Gemfile", "Gemfile.lock"]

social-links:
  twitter: 'https://twitter.com/netlify'
  facebook: 'https://www.facebook.com/netlify'
  github: 'https://github.com/netlify'
  linkedin: 'https://www.linkedin.com/company/netlify'
  googleplus: 'https://plus.google.com/+NetlifyApp'

